-- Create shadow tables for PCBS1 with identical schema to existing PCBS2 tables
CREATE TABLE IF NOT EXISTS v1_cpu (LIKE cpu INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v1_gpu (LIKE gpu INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v1_ram (LIKE ram INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v1_motherboard (LIKE motherboard INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v1_psu (LIKE psu INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v1_storage (LIKE storage INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v1_cases (LIKE cases INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v1_coolers (LIKE coolers INCLUDING ALL);
