-- Create shadow tables for PCBS2 with identical schema to existing PCBS1 tables
CREATE TABLE IF NOT EXISTS v2_cpu (LIKE cpu INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v2_gpu (LIKE gpu INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v2_ram (LIKE ram INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v2_motherboard (LIKE motherboard INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v2_psu (LIKE psu INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v2_storage (LIKE storage INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v2_cases (LIKE cases INCLUDING ALL);
CREATE TABLE IF NOT EXISTS v2_coolers (LIKE coolers INCLUDING ALL);
